

trazPDF:
	sshpass -p '3cr96ipzS' scp elias@www.eliasdeoliveira.com.br:/var/www/seminars/tmp/*.pdf . & >/dev/null 2>&1


trazTXT:
	sshpass -p '3cr96ipzS' scp elias@www.eliasdeoliveira.com.br:/var/www/seminars/tmp/*.txt . & >/dev/null 2>&1
